# Generated by Django 5.2 on 2025-05-02 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('country', models.TextField(max_length=250)),
                ('city', models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='LinkStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_owner', models.BooleanField(default=False)),
                ('created_at', models.TimeField(auto_now_add=True)),
                ('is_mobile', models.BooleanField(default=False)),
                ('browser_name', models.BooleanField(default=False)),
                ('follower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='analytics.follower')),
            ],
        ),
    ]
