# Generated by Django 5.2 on 2025-05-02 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkstats',
            name='link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='links.link'),
        ),
    ]
