# Generated by Django 5.2 on 2025-05-09 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkstats',
            name='is_mobile',
        ),
        migrations.AddField(
            model_name='linkstats',
            name='device',
            field=models.TextField(default='pc', max_length=6),
        ),
        migrations.AlterField(
            model_name='linkstats',
            name='browser_name',
            field=models.TextField(max_length=30),
        ),
    ]
