# Generated by Django 5.2 on 2025-06-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_remove_linkstats_is_mobile_linkstats_device_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkstats',
            name='os_name',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='linkstats',
            name='os_version',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='linkstats',
            name='browser_name',
            field=models.TextField(max_length=20),
        ),
    ]
