# Generated by Django 5.2 on 2025-06-08 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_linkstats_os_name_linkstats_os_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkstats',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
