# Generated by Django 5.2 on 2025-06-08 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_alter_linkstats_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkstats',
            name='user_id',
            field=models.PositiveIntegerField(default=9),
            preserve_default=False,
        ),
    ]
