# Generated by Django 5.2 on 2025-06-10 17:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_linkstats_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkstats',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
