# Generated by Django 5.2 on 2025-05-25 17:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_validation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationmodel',
            name='sent_mail_to_user_counter',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emailverificationmodel',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailverificationmodel',
            name='time_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
