# Generated by Django 5.2 on 2025-05-02 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=32, null=True)),
                ('source_link', models.TextField(max_length=250)),
                ('short_link', models.TextField(max_length=10)),
            ],
        ),
    ]
