# Generated by Django 5.2 on 2025-05-14 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_alter_link_short_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='short_link',
            field=models.TextField(max_length=15, unique=True),
        ),
    ]
