# Generated by Django 5.2 on 2025-05-18 12:19

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0004_alter_link_short_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='link',
            index=django.contrib.postgres.indexes.HashIndex(fields=['short_link'], name='hash_index_short_link'),
        ),
    ]
